module.exports = {
  title: "Stanley Liu | Software Engineer",
  description:
    "Stanley Liu is a software engineer focusing on designing and building exceptional web applications",
  url: "https://stanliu.netlify.app",
  image: "src/images/logo.png",
  imageWidth: 0,
  imageHeight: 0,
  language: "en",
  ogLanguage: "en_US",
  email: "stanleyliu15.dev@gmail.com",
  twitter: "stanley_liu15",
  github: "stanleyliu15",
  linkedin: "stanleyliu15",
  keywords: "Stanley Liu",
  author: "Stanley Liu",
  shortName: "Stanley Liu",
  favicon: "src/images/logo.png",
  themeColor: "#324234",
  backgroundColor: "#eee",
}
